version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    networks: [webnet]

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pronka
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pronkadatabase
    volumes:
      -  db_data:/var/lib/postgresql/data

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      -  "80:80"
      -  "443:443"
    volumes:
      -  ./Caddyfile:/etc/caddy/Caddyfile:ro
      -  caddy_data:/data
      -  caddy_config:/config
    networks: [webnet]

networks:
  webnet:


volumes:
  db_data:
  caddy_data:
  caddy_config:
