version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db


  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pronka
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pronkadatabase
    volumes:
      -  db_data:/var/lib/postgresql/data

volumes:
  db_data:

